import { useEffect, useMemo, useState } from 'react'
import { ArrowDown, ArrowUpRight, Check, ChevronDown, ChevronRight, CircleHelp, CloudRain, Droplets, Flame, Heart, Home, Leaf, Plus, Settings2, Shield, ShieldCheck, Sparkles, Sun, Users, X } from 'lucide-react'

const KEY='refugio-v1', icons=['🧑🏽‍🚒','👩🏻‍🌾','🧑🏾‍🔧','👩🏽‍⚕️','🧑🏻‍🚀','🐻','🦊','🐸','🦉','🐢','🐱','🦋'], palette=['#dff2eb','#ffedda','#eee8ff','#ffe6e3','#e5efff','#fff4c9','#e9f1e6','#f8e2f0']
const catalog=[
 ['water','Preparar el agua de reserva','Guarda agua potable en recipientes limpios y cerrados. Referencia: 14–21 L por persona para 7 días.','Agua','💧',35,'Imprescindible'],
 ['readyfood','Separar comida que no requiere cocción','Prioriza atún, sardinas, galletas, frutos secos y barras.','Alimentos','🥫',30,'Imprescindible'],
 ['dryfood','Revisar la despensa de alimentos secos','Cuenta arroz, lentejas, fréjol, pasta, avena y harinas.','Alimentos','🍚',25,'Imprescindible'],
 ['light','Probar linternas y pilas de repuesto','Revisa también la lámpara recargable si tienen una.','Energía','🔦',25,'Imprescindible'],
 ['radio','Probar la radio y cargar los power banks','Deja cables de carga junto a los equipos.','Comunicaciones','📻',25,'Imprescindible'],
 ['firstaid','Completar el botiquín familiar','Revisa gasas, vendas, antiséptico, termómetro y medicinas habituales.','Salud','🩹',30,'Imprescindible'],
 ['repellent','Reponer repelente y artículos de higiene','Incluye jabón, papel higiénico, alcohol y bolsas de basura.','Salud','🦟',25,'Imprescindible'],
 ['floodkit','Preparar el kit para lluvias e inundación','Junta sacos resistentes, plástico, cinta, baldes y guantes impermeables.','Inundación','🌧️',35,'Imprescindible'],
 ['boots','Revisar botas de caucho e impermeables','Deja calzado cerrado y ropa de lluvia accesibles.','Inundación','🥾',20,'Imprescindible'],
 ['documents','Guardar copias y contactos en funda impermeable','Incluye documentos importantes y algo de efectivo.','Familia','📄',30,'Imprescindible'],
 ['bag','Armar la mochila de emergencia','Agua, comida lista, linterna, radio, botiquín, higiene y documentos.','Evacuación','🎒',40,'Imprescindible'],
 ['pets','Preparar el kit de 72 horas de las mascotas','Agua, alimento, recipiente, correa y medicinas si usan.','Mascotas','🐾',25,'Recomendable'],
 ['tools','Revisar herramientas básicas','Cinta americana, cuerda, alicate, destornillador, guantes y navaja.','Herramientas','🧰',25,'Recomendable'],
 ['watercare','Identificar recipientes y potabilizador apropiado','Sigue exactamente la etiqueta del producto para potabilizar agua.','Agua','🫗',25,'Recomendable'],
 ['mosquito','Eliminar agua estancada del patio','Hazlo cuando sea seguro y sin entrar en agua de inundación.','Hogar','🪣',25,'Recomendable'],
 ['routes','Acordar ruta segura y punto de encuentro','Conversen en familia y sigan las indicaciones oficiales.','Familia','🧭',30,'Recomendable'],
 ['roof','Revisar cierres y filtraciones desde un lugar seguro','No subas a techos ni te acerques a cables o equipos mojados.','Hogar','🏠',25,'Recomendable'],
 ['food15','Definir compras graduales para ampliar la despensa','Agrega UHT, avena, conservas, frutos secos y alimentos habituales.','Alimentos','🛒',20,'Opcional'],
 ['shelter','Revisar elementos adicionales de seguridad del hogar','Considera extintor y detector de humo según tu vivienda.','Hogar','🧯',25,'Opcional'],
 ['watercheck','Revisar fecha y estado de la reserva de agua','Mantén los recipientes cerrados, limpios y protegidos.','Agua','🔄',20,'Recomendable'],
]
const todayKey=()=>new Intl.DateTimeFormat('en-CA').format(new Date())
function initial(){const missions=catalog.map((m,i)=>({id:m[0],title:m[1],detail:m[2],category:m[3],icon:m[4],xp:m[5],priority:m[6],owner:i<3?'p1':i<5?'p2':null,done:false,due:i<5?'today':'future'}));return {family:{name:'Familia Rivera',week:1},players:[{id:'p1',name:'Alex',emoji:'🧑🏽‍🚒',color:palette[0],level:4,xp:260,hp:82},{id:'p2',name:'Mamá',emoji:'👩🏻‍🌾',color:palette[1],level:3,xp:180,hp:100},{id:'p3',name:'Papá',emoji:'🧑🏾‍🔧',color:palette[2],level:2,xp:95,hp:68}],missions,daily:{date:todayKey(),base:{p1:82,p2:100,p3:68}},activity:[]}}
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s){if(s.daily?.date!==todayKey()){s.daily={date:todayKey(),base:Object.fromEntries(s.players.map(p=>[p.id,p.hp]))};s.missions=s.missions.map(m=>({...m,done:false,due:m.due==='today'?'today':'future'}))}return s}}catch{}return initial()}
const clamp=n=>Math.max(0,Math.min(100,n))
export default function App(){
 const [data,setData]=useState(load),[active,setActive]=useState('p1'),[tab,setTab]=useState('missions'),[showAll,setShowAll]=useState(false),[showEditor,setShowEditor]=useState(false),[newName,setNewName]=useState(''),[showFamily,setShowFamily]=useState(false)
 const player=data.players.find(p=>p.id===active)||data.players[0], todays=data.missions.filter(m=>m.due==='today'),doneCount=todays.filter(m=>m.done).length,readyNext=todays.length>0&&doneCount===todays.length
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(data)),[data])
 const hp=useMemo(()=>{const start=data.daily.base[player.id]??player.hp;const midnight=new Date();midnight.setHours(0,0,0,0);return clamp(start-Math.max(0,(Date.now()-midnight.getTime())/86400000)*10+todays.filter(m=>m.done&&m.owner===player.id).length*7)},[data,player.id,todays])
 const list=tab==='missions'?(showAll?todays:todays.filter(m=>!m.owner||m.owner===player.id)):[]
 function update(fn){setData(d=>{const n=structuredClone(d);fn(n);return n})}
 function take(id){update(d=>{const m=d.missions.find(x=>x.id===id);if(m&&!m.owner)m.owner=active})}
 function complete(id){update(d=>{const m=d.missions.find(x=>x.id===id);if(!m||m.owner!==active||m.done)return; m.done=true;const p=d.players.find(x=>x.id===active);p.xp+=m.xp;if(p.xp>=p.level*100){p.xp-=p.level*100;p.level++}d.activity.unshift({text:`${p.name} completó «${m.title}»`,time:'ahora',emoji:p.emoji})})}
 function advance(){update(d=>{const m=d.missions.find(x=>x.due==='future'&&x.priority!=='Opcional');if(m){m.due='today';m.owner=active;d.family.week++}});setShowAll(false)}
 function addPlayer(){const name=newName.trim();if(!name)return;const id=crypto.randomUUID();update(d=>{d.players.push({id,name,emoji:icons[d.players.length%icons.length],color:palette[d.players.length%palette.length],level:1,xp:0,hp:100});d.daily.base[id]=100});setActive(id);setNewName('')}
 function avatar(emoji,color){update(d=>{const p=d.players.find(x=>x.id===active);p.emoji=emoji;p.color=color})}
 return <div className="app-shell"><header className="topbar"><a className="brand" href="#"><span className="brand-icon"><ShieldCheck size={19}/></span><span>refugio<span className="brand-dot">.</span></span></a><div className="top-right"><button className="family-switch" onClick={()=>setShowFamily(!showFamily)}><span className="family-emblem">🏡</span><span><strong>{data.family.name}</strong><small>Mi hogar</small></span><ChevronDown size={15}/></button><button className="help-btn" title="Ayuda"><CircleHelp size={19}/></button></div></header>
 <main className="layout"><aside className="sidebar"><div className="side-label">TU FAMILIA <button title="Agregar habitante" onClick={()=>setShowEditor(true)}><Plus size={15}/></button></div><div className="player-list">{data.players.map(p=><button key={p.id} className={`player-row ${p.id===active?'selected':''}`} onClick={()=>setActive(p.id)}><span className="avatar-small" style={{background:p.color}}>{p.emoji}</span><span className="player-name"><strong>{p.name}</strong><small>Nivel {p.level}</small></span>{p.id===active&&<span className="active-dot"/>}</button>)}</div><div className="side-card"><span className="mini-label"><Sparkles size={13}/> ESTA SEMANA</span><div className="weekly-number">{data.missions.filter(m=>m.done).length}<span>/{data.missions.length} misiones</span></div><div className="progress-track"><span style={{width:`${data.missions.filter(m=>m.done).length/data.missions.length*100}%`}}/></div><small>¡Cada pequeño paso nos prepara!</small></div><div className="side-foot"><Shield size={15}/> Espacio privado de tu familia</div></aside>
 <section className="main-content"><div className="welcome-row"><div><div className="eyebrow"><span className="live-dot"/> PLAN FAMILIAR · SEMANA {String(data.family.week).padStart(2,'0')}</div><h1>Hola, {player.name} <span className="wave">✳</span></h1><p>Un paso a la vez, nos preparamos juntos.</p></div><button className="week-button" onClick={()=>setTab('missions')}><Sun size={16}/> Semana {data.family.week}<ChevronDown size={14}/></button></div>
 <div className="stats-grid"><div className="stat-card hp-card"><div className="stat-head"><span className="stat-icon heart-icon"><Heart size={17} fill="currentColor"/></span><span className="stat-label">ENERGÍA DE HOY</span><span className="stat-value">{Math.round(hp)}<small>/100</small></span></div><div className="hp-track"><span style={{width:`${hp}%`}}/></div><div className="stat-foot"><span>{hp>60?'Vas muy bien, sigue así':hp>30?'Un pequeño paso te dará energía':'Completa una misión para recuperar energía'}</span><span className="hp-status">● {hp>60?'Saludable':hp>30?'Cuidándote':'Baja'}</span></div></div><div className="stat-card streak-card"><div className="stat-head"><span className="stat-icon flame-icon"><Flame size={17}/></span><span className="stat-label">RACHA FAMILIAR</span></div><div className="streak-value">{Math.max(1,Math.min(7,data.missions.filter(m=>m.done).length))}<small> días</small><span className="streak-glyph">✦</span></div><div className="stat-foot"><span>¡Se están apoyando muy bien!</span></div></div><div className="stat-card level-card"><div className="stat-head"><span className="stat-icon leaf-icon"><Leaf size={17}/></span><span className="stat-label">TU PROGRESO</span></div><div className="level-row"><strong>Nivel {player.level}</strong><span>{player.xp}/{player.level*100} XP</span></div><div className="progress-track level-track"><span style={{width:`${player.xp/(player.level*100)*100}%`}}/></div><div className="stat-foot"><span>Preparador en crecimiento</span></div></div></div>
 <div className="section-tabs"><button className={tab==='missions'?'tab-active':''} onClick={()=>setTab('missions')}><ShieldCheck size={16}/> Misiones <span className="tab-count">{todays.length-doneCount}</span></button><button className={tab==='family'?'tab-active':''} onClick={()=>setTab('family')}><Users size={16}/> Actividad familiar</button></div>
 {tab==='missions'?<><div className="mission-heading"><div><h2>Tu plan de hoy <span className="today-pill">{doneCount}/{todays.length}</span></h2><p>Misiones pequeñas para un hogar más preparado.</p></div><button className="filter-button" onClick={()=>setShowAll(!showAll)}><Settings2 size={15}/>{showAll?'Todas las de hoy':'Mis asignadas'}<ChevronDown size={14}/></button></div>
 {!readyNext?<div className="mission-list">{list.map(m=><article className={`mission-card ${m.done?'mission-done':''}`} key={m.id}><span className="mission-emoji">{m.icon}</span><div className="mission-info"><div className="mission-title-row"><h3>{m.title}</h3><span className="category-tag">{m.category}</span></div><p>{m.detail}</p><span className="mission-reward"><Sparkles size={12}/> +{m.xp} XP · {m.priority}</span>{m.owner&&<span className="owner-label">{m.owner===active?'Tu misión':data.players.find(p=>p.id===m.owner)?.name+' la tiene'}</span>}</div><div className="mission-action">{m.done?<span className="done-check"><Check size={16}/></span>:m.owner===active?<button className="complete-button" onClick={()=>complete(m.id)}>Completar <ChevronRight size={14}/></button>:m.owner?<span className="taken-label">En progreso</span>:<button className="claim-button" onClick={()=>take(m.id)}>Tomar misión <ArrowDown size={14}/></button>}</div></article>)}</div>:<div className="next-panel"><div className="next-art"><span>🌤️</span><Sparkles size={17}/></div><div><span className="eyebrow">¡PLAN DE HOY COMPLETADO!</span><h3>La familia ya hizo su parte.</h3><p>¿Tienes energía para adelantar una misión de la reserva? Quedará asignada solo para ti.</p><button className="primary-button" onClick={advance}>Adelantar una misión <ArrowUpRight size={16}/></button></div></div>}
 <div className="week-progress"><div><span>PREPARACIÓN DE ESTA SEMANA</span><strong>{data.missions.filter(m=>m.done).length} de {data.missions.length} listas</strong></div><div className="progress-track"><span style={{width:`${data.missions.filter(m=>m.done).length/data.missions.length*100}%`}}/></div><button onClick={()=>setShowAll(true)}>Ver plan semanal <ChevronRight size={14}/></button></div></>:<div className="activity-list">{data.activity.map((a,i)=><article key={i} className="activity-item"><span className="avatar-small" style={{background:palette[i%palette.length]}}>{a.emoji}</span><div><strong>{a.text}</strong><small>{a.time}</small></div><Check size={16}/></article>)}{!data.activity.length&&<p>Aún no hay actividad. ¡Completen juntos la primera misión!</p>}</div>}
 <div className="safety-note"><span><CloudRain size={17}/></span><p><strong>Prepararse también es cuidarnos.</strong> Nunca manipules cables o equipos eléctricos en zonas mojadas ni camines por agua de inundación. Sigue las indicaciones oficiales locales.</p><ArrowUpRight size={15}/></div></section>
 <aside className="right-panel"><div className="profile-card"><div className="profile-head"><div><span className="eyebrow">TU PERSONAJE</span><button className="edit-avatar" onClick={()=>setShowEditor(true)}><Settings2 size={15}/></button></div><span className="edit-caption" onClick={()=>setShowEditor(true)}>Editar</span></div><div className="hero-avatar" style={{background:player.color}}><span>{player.emoji}</span><span className="avatar-spark">✦</span></div><h2>{player.name}</h2><span className="role-label">GUARDIÁN DEL HOGAR</span><div className="profile-stats"><div><span>NIVEL</span><strong>{player.level}</strong></div><div><span>XP TOTAL</span><strong>{player.xp}</strong></div><div><span>ENERGÍA</span><strong>{Math.round(hp)}%</strong></div></div><button className="customize-button" onClick={()=>setShowEditor(true)}><Sparkles size={15}/> Personalizar personaje</button></div><div className="family-card"><div className="family-card-title"><span className="mini-icon"><Home size={15}/></span><strong>Tu refugio familiar</strong></div><p>{data.players.length} habitantes preparándose juntos.</p><div className="family-avatars">{data.players.map(p=><span key={p.id} style={{background:p.color}}>{p.emoji}</span>)}<button onClick={()=>setShowEditor(true)}><Plus size={15}/></button></div><div className="family-divider"/><div className="family-metric"><span><Droplets size={14}/> Reserva de agua</span><strong>En preparación</strong></div><div className="family-metric"><span><ShieldCheck size={14}/> Misiones listas</span><strong>{data.missions.filter(m=>m.done).length}/{data.missions.length}</strong></div></div><div className="quote-card"><span>✳</span><p>“La preparación es un acto de amor hacia nuestra familia.”</p><small>— Juntos somos más fuertes</small></div></aside></main>
 {showEditor&&<div className="modal-scrim" onMouseDown={e=>e.target===e.currentTarget&&setShowEditor(false)}><div className="modal"><div className="modal-heading"><div><span className="eyebrow">TU PERSONAJE</span><h2>Personaliza tu avatar</h2></div><button className="icon-button" onClick={()=>setShowEditor(false)}><X size={19}/></button></div><div className="avatar-preview" style={{background:player.color}}>{player.emoji}</div><label className="field-label">Elige tu avatar</label><div className="emoji-grid">{icons.map(i=><button className={i===player.emoji?'choice-selected':''} key={i} onClick={()=>avatar(i,player.color)}>{i}</button>)}</div><label className="field-label">Color de fondo</label><div className="color-grid">{palette.map(c=><button key={c} className={c===player.color?'color-selected':''} style={{background:c}} onClick={()=>avatar(player.emoji,c)}/>)}</div><div className="family-divider"/><label className="field-label">Agregar habitante a la familia</label><div className="add-player"><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Nombre del jugador" onKeyDown={e=>e.key==='Enter'&&addPlayer()}/><button onClick={addPlayer} disabled={!newName.trim()}><Plus size={16}/> Agregar</button></div><div className="member-list">{data.players.map(p=><button key={p.id} onClick={()=>setActive(p.id)} className={p.id===active?'member-active':''}><span style={{background:p.color}}>{p.emoji}</span>{p.name}{p.id===active&&<Check size={15}/>}</button>)}</div><button className="primary-button save-button" onClick={()=>setShowEditor(false)}>Listo <Check size={16}/></button></div></div>}
 {showFamily&&<div className="family-popover"><span className="family-emblem">🏡</span><div><strong>{data.family.name}</strong><p>Datos guardados solo en este dispositivo.</p></div><button onClick={()=>setShowFamily(false)}><X size={15}/></button></div>}<nav className="mobile-nav"><button onClick={()=>setTab('missions')} className={tab==='missions'?'mobile-active':''}><ShieldCheck size={18}/>Misiones</button><button onClick={()=>setTab('family')} className={tab==='family'?'mobile-active':''}><Users size={18}/>Familia</button><button onClick={()=>setShowEditor(true)}><Sparkles size={18}/>Avatar</button></nav></div>
}
